targets:
  $default:
    builders:
      drift_dev:analyzer:
        options: &drift_options
          store_date_time_values_as_text: true
          named_parameters: true
      drift_dev:modular:
        options: *drift_options
