"""Draws the Workout Log launcher icon.

The mark is the app's own weekly-volume chart: four bars rising left to right,
coloured with the body-part palette from `docs/02-ROUTINE-SEED.md`. Ascending
heights read as progress, which is what the app records.

Deliberately drawn rather than generated by a diffusion model: a launcher icon
has to stay crisp at 48 px, and flat geometry survives that scale where an
illustration does not.

Run with any Python that has Pillow:

    python tools/generate_icon.py

Outputs `assets/icon/icon.png` (full, 1024) and `assets/icon/icon_foreground.png`
(Android adaptive foreground, content inside the 66% safe zone).
Then regenerate the launcher assets:

    dart run flutter_launcher_icons
"""

from pathlib import Path

from PIL import Image, ImageDraw

SIZE = 1024
SUPERSAMPLE = 4  # draw large, downscale — gives clean rounded corners
CANVAS = SIZE * SUPERSAMPLE

BACKGROUND = (18, 21, 26, 255)  # near --plane of the dark theme
CORNER_RADIUS = 0.22  # fraction of the side

# Weekly set counts of the reference routine, ascending so the chart climbs.
# (label, weekly sets, body-part colour)
BARS = [
    ("legs", 12, (47, 169, 140, 255)),  # --legs
    ("back", 16, (59, 125, 216, 255)),  # --back
    ("chest", 17, (217, 79, 112, 255)),  # --chest
    ("shoulder", 19, (224, 145, 47, 255)),  # --shoulder
]

BAR_WIDTH = 0.136  # fraction of the icon side
BAR_GAP = 0.058
TALLEST = 0.50  # height of the tallest bar
BASELINE = 0.775  # y of the bar feet


def draw_bars(draw: ImageDraw.ImageDraw, scale: float, offset_y: float = 0.0) -> None:
    """Draws the bar group centred horizontally.

    [scale] shrinks the group for the adaptive foreground's safe zone;
    [offset_y] nudges it back to the optical centre after shrinking.
    """
    unit = CANVAS
    bar_w = BAR_WIDTH * unit * scale
    gap = BAR_GAP * unit * scale
    group_w = len(BARS) * bar_w + (len(BARS) - 1) * gap
    left = (unit - group_w) / 2
    baseline = BASELINE * unit * scale + offset_y
    tallest_sets = max(sets for _, sets, _ in BARS)
    radius = bar_w / 2

    for index, (_, sets, colour) in enumerate(BARS):
        height = TALLEST * unit * scale * (sets / tallest_sets)
        x0 = left + index * (bar_w + gap)
        draw.rounded_rectangle(
            [x0, baseline - height, x0 + bar_w, baseline],
            radius=radius,
            fill=colour,
        )


def render(with_background: bool, scale: float, offset_y: float) -> Image.Image:
    image = Image.new("RGBA", (CANVAS, CANVAS), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    if with_background:
        draw.rounded_rectangle(
            [0, 0, CANVAS - 1, CANVAS - 1],
            radius=CORNER_RADIUS * CANVAS,
            fill=BACKGROUND,
        )

    draw_bars(draw, scale=scale, offset_y=offset_y)
    return image.resize((SIZE, SIZE), Image.LANCZOS)


def main() -> None:
    out_dir = Path(__file__).resolve().parent.parent / "assets" / "icon"
    out_dir.mkdir(parents=True, exist_ok=True)

    render(with_background=True, scale=1.0, offset_y=0.0).save(out_dir / "icon.png")

    # The adaptive foreground is drawn full-bleed: flutter_launcher_icons wraps
    # it in a 16% inset, which is what pulls the mark inside the ~66% safe zone
    # a circular mask leaves visible. Shrinking it here as well would double the
    # inset and leave a stamp-sized logo.
    #
    # Only the vertical offset changes: the bars hang off a baseline in the full
    # icon, so the group has to be nudged up to sit on the drawable's centre.
    group_centre = BASELINE - TALLEST / 2
    render(
        with_background=False,
        scale=1.0,
        offset_y=-CANVAS * (group_centre - 0.5),
    ).save(out_dir / "icon_foreground.png")

    print(f"wrote {out_dir / 'icon.png'}")
    print(f"wrote {out_dir / 'icon_foreground.png'}")


if __name__ == "__main__":
    main()
